const $=id=>document.getElementById(id);
const canvas=new fabric.Canvas("editorCanvas",{preserveObjectStacking:true,selection:true});
let history=[],future=[],restoring=false,cropTarget=null,github=null,lastBlob=null,recentFrames=[];
const state={name:"Untitled Asset",canvasWidth:1024,canvasHeight:1024};
const setStatus=s=>$("status").textContent=s;
const toast=s=>{const t=$("toast");t.textContent=s;t.className="show";clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.className="",2200)};
function snapshot(){if(restoring)return;const j=JSON.stringify(canvas.toJSON(["name","assetId"]));if(history.at(-1)!==j){history.push(j);if(history.length>80)history.shift();future=[]}}
async function restore(j){restoring=true;await canvas.loadFromJSON(JSON.parse(j));canvas.renderAll();syncProps();restoring=false}
function resizeEditor(){const w=+$("cw").value||1024,h=+$("ch").value||1024;state.canvasWidth=w;state.canvasHeight=h;canvas.setDimensions({width:w,height:h});$("dimensions").textContent=w+" × "+h;fit()}
function fit(){const st=$("stage"),z=Math.min((st.clientWidth-48)/canvas.width,(st.clientHeight-48)/canvas.height,1);canvas.setZoom(z);canvas.setDimensions({width:canvas.width*z,height:canvas.height*z},"cssOnly");$("zoomLabel").textContent=Math.round(z*100)+"%"}
window.addEventListener("resize",fit);

async function addRasterBlob(blob,name="asset.png"){const url=URL.createObjectURL(blob);try{return await addRasterUrl(url,name)}finally{URL.revokeObjectURL(url)}}
async function addRasterUrl(url,name="asset.png"){const img=await fabric.FabricImage.fromURL(url,{crossOrigin:"anonymous"}),w=+$("cw").value||1024,h=+$("ch").value||1024,s=Math.min((w*.82)/img.width,(h*.82)/img.height,1);img.set({left:(w-img.width*s)/2,top:(h-img.height*s)/2,scaleX:s,scaleY:s,name,angle:0});canvas.add(img);canvas.setActiveObject(img);canvas.renderAll();$("dropHint").style.display="none";snapshot();syncProps();return img}
async function upload(file){if(!file)return;setStatus("Loading image…");try{await addRasterBlob(file,file.name);setStatus("Ready")}catch(e){console.error(e);toast("Image import failed");setStatus("Ready")}}
$("uploadBtn").onclick=()=>$("fileInput").click();$("fileInput").onchange=e=>upload(e.target.files[0]);
$("stage").ondragover=e=>{e.preventDefault();$("stage").classList.add("drop-active")};$("stage").ondragleave=()=>$("stage").classList.remove("drop-active");$("stage").ondrop=e=>{e.preventDefault();$("stage").classList.remove("drop-active");upload(e.dataTransfer.files[0])};

function syncProps(){const o=canvas.getActiveObject();$("propsEmpty").classList.toggle("hidden",!!o);$("props").classList.toggle("hidden",!o);if(!o)return;for(const [id,v] of [["px",o.left||0],["py",o.top||0],["pw",o.getScaledWidth()||0],["ph",o.getScaledHeight()||0],["prot",o.angle||0],["pop",o.opacity??1]])$(id).value=Math.round(v*100)/100;$("imageControls").classList.toggle("hidden",o.type!=="image")}
function updateProps(){const o=canvas.getActiveObject();if(!o)return;o.set({left:+$("px").value||0,top:+$("py").value||0,angle:+$("prot").value||0,opacity:+$("pop").value});const w=+$("pw").value,h=+$("ph").value;if(w>0&&o.width)o.scaleX=w/o.width;if(h>0&&o.height)o.scaleY=h/o.height;canvas.requestRenderAll();snapshot()}
["px","py","pw","ph","prot","pop"].forEach(id=>$(id).onchange=updateProps);
$("deleteBtn").onclick=()=>{const o=canvas.getActiveObject();if(o){canvas.remove(o);snapshot();syncProps()}};
$("duplicateBtn").onclick=async()=>{const o=canvas.getActiveObject();if(!o)return;const c=await o.clone();c.set({left:(o.left||0)+20,top:(o.top||0)+20,name:(o.name||"asset")+"_copy"});canvas.add(c);canvas.setActiveObject(c);snapshot()};
$("textBtn").onclick=()=>{const t=new fabric.IText("Game Asset",{left:100,top:100,fill:"#fff",fontSize:64,fontFamily:"Arial",fontWeight:"700"});canvas.add(t);canvas.setActiveObject(t);snapshot()};
$("rectBtn").onclick=()=>{const r=new fabric.Rect({left:100,top:100,width:240,height:160,fill:"#3b82f6",rx:16,ry:16});canvas.add(r);canvas.setActiveObject(r);snapshot()};

function applyFilters(){const o=canvas.getActiveObject();if(!o||o.type!=="image")return;const vals=[+$("brightness").value,+$("contrast").value,+$("saturation").value,+$("blur").value];o.filters=[new fabric.filters.Brightness({brightness:vals[0]}),new fabric.filters.Contrast({contrast:vals[1]}),new fabric.filters.Saturation({saturation:vals[2]}),new fabric.filters.Blur({blur:vals[3]})].filter((_,i)=>vals[i]!==0);o.applyFilters();canvas.requestRenderAll();snapshot()}
["brightness","contrast","saturation","blur"].forEach(id=>$(id).oninput=applyFilters);
$("resetFilters").onclick=()=>{const o=canvas.getActiveObject();if(o?.type!=="image")return;o.filters=[];o.applyFilters();["brightness","contrast","saturation","blur"].forEach(id=>$(id).value=0);canvas.requestRenderAll();snapshot()};

async function addReplacement(blob,old,name){const url=URL.createObjectURL(blob);try{const n=await fabric.FabricImage.fromURL(url);n.set({left:old.left,top:old.top,angle:old.angle,opacity:old.opacity,scaleX:old.scaleX,scaleY:old.scaleY,name});canvas.remove(old);canvas.add(n);canvas.setActiveObject(n);canvas.renderAll();snapshot();syncProps();await vaultPut(blob,name);lastBlob=blob;return n}finally{URL.revokeObjectURL(url)}}
async function imageFromCrop(obj,x,y,w,h){const src=obj.getElement(),out=document.createElement("canvas");out.width=w;out.height=h;out.getContext("2d").drawImage(src,x,y,w,h,0,0,w,h);const blob=await new Promise(r=>out.toBlob(r,"image/png",1));return addReplacement(blob,obj,(obj.name||"asset").replace(/\.[^.]+$/,"")+"_crop.png")}
function updateCropBox(){if(!cropTarget)return;const img=$("cropPreview"),box=$("cropBox"),x=+$("cropX").value||0,y=+$("cropY").value||0,w=+$("cropW").value||1,h=+$("cropH").value||1,iw=cropTarget.getElement().naturalWidth||cropTarget.width,ih=cropTarget.getElement().naturalHeight||cropTarget.height,rw=img.clientWidth||1,rh=img.clientHeight||1,ox=(img.parentElement.clientWidth-rw)/2,oy=(img.parentElement.clientHeight-rh)/2;box.style.left=(ox+x/iw*rw)+"px";box.style.top=(oy+y/ih*rh)+"px";box.style.width=(w/iw*rw)+"px";box.style.height=(h/ih*rh)+"px"}
function openCrop(){const o=canvas.getActiveObject();if(!o||o.type!=="image")return toast("Select an image first");cropTarget=o;const src=o.getElement();$("cropPreview").src=src.currentSrc||src.src;const iw=src.naturalWidth||o.width,ih=src.naturalHeight||o.height;$("cropX").value=0;$("cropY").value=0;$("cropW").value=iw;$("cropH").value=ih;$("cropModal").classList.remove("hidden");setTimeout(updateCropBox,50)}
["cropX","cropY","cropW","cropH"].forEach(id=>$(id).oninput=updateCropBox);$("cropBtn").onclick=openCrop;
$("applyCrop").onclick=async()=>{if(!cropTarget)return;const src=cropTarget.getElement(),maxW=src.naturalWidth||cropTarget.width,maxH=src.naturalHeight||cropTarget.height;let x=Math.max(0,Math.min(maxW-1,+$("cropX").value||0)),y=Math.max(0,Math.min(maxH-1,+$("cropY").value||0)),w=Math.max(1,Math.min(maxW-x,+$("cropW").value||maxW-x)),h=Math.max(1,Math.min(maxH-y,+$("cropH").value||maxH-y));$("applyCrop").disabled=true;try{await imageFromCrop(cropTarget,x,y,w,h);$("cropModal").classList.add("hidden");toast("Crop applied")}catch(e){console.error(e);toast("Crop failed")}finally{$("applyCrop").disabled=false;cropTarget=null}};
document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>$(b.dataset.close).classList.add("hidden"));

async function trimTransparent(){const o=canvas.getActiveObject();if(!o||o.type!=="image")return toast("Select a transparent image first");const src=o.getElement(),c=document.createElement("canvas");c.width=src.naturalWidth||o.width;c.height=src.naturalHeight||o.height;const ctx=c.getContext("2d",{willReadFrequently:true});ctx.drawImage(src,0,0,c.width,c.height);const d=ctx.getImageData(0,0,c.width,c.height).data;let minX=c.width,minY=c.height,maxX=-1,maxY=-1;for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++){if(d[(y*c.width+x)*4+3]>4){if(x<minX)minX=x;if(x>maxX)maxX=x;if(y<minY)minY=y;if(y>maxY)maxY=y}}if(maxX<0)return toast("No visible pixels found");const out=document.createElement("canvas");out.width=maxX-minX+1;out.height=maxY-minY+1;out.getContext("2d").drawImage(c,minX,minY,out.width,out.height,0,0,out.width,out.height);const blob=await new Promise(r=>out.toBlob(r,"image/png",1));await addReplacement(blob,o,(o.name||"asset").replace(/\.[^.]+$/,"")+"_trim.png");toast("Transparent bounds trimmed")}
$("trimBtn").onclick=trimTransparent;

async function removeBg(){const o=canvas.getActiveObject();if(!o||o.type!=="image")return toast("Select an image first");$("bgBtn").disabled=true;setStatus("AI background removal…");try{const {default:removeBackground}=await import("https://cdn.jsdelivr.net/npm/@imgly/background-removal@1.7.0/+esm");const blob=await removeBackground(o.getElement(),{device:"gpu",output:{format:"image/png",quality:1,type:"foreground"},progress:(k,c,t)=>setStatus("AI "+k+" "+c+"/"+t)});await addReplacement(blob,o,(o.name||"asset").replace(/\.[^.]+$/,"")+"_cutout.png");toast("Background removed");setStatus("Ready")}catch(e){console.error(e);toast("Background removal failed — original kept");setStatus("Ready")}finally{$("bgBtn").disabled=false}}
$("bgBtn").onclick=removeBg;

function db(){return new Promise((res,rej)=>{const r=indexedDB.open("asset-forge-v2",1);r.onupgradeneeded=()=>r.result.createObjectStore("assets",{keyPath:"id"});r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function vaultPut(blob,name,remote=false){const d=await db(),tx=d.transaction("assets","readwrite");tx.objectStore("assets").put({id:crypto.randomUUID(),name,blob,remote,created:Date.now()});tx.oncomplete=renderVault}
async function renderVault(){const d=await db(),r=d.transaction("assets","readonly").objectStore("assets").getAll();r.onsuccess=()=>{$("vault").innerHTML="";for(const a of r.result.sort((x,y)=>y.created-x.created)){const el=document.createElement("div");el.className="asset";const img=document.createElement("img");img.src=URL.createObjectURL(a.blob);const sm=document.createElement("small");sm.textContent=(a.remote?"☁ ":"")+a.name;el.append(img,sm);el.onclick=async()=>addRasterBlob(a.blob,a.name);$("vault").appendChild(el)}}}
$("clearVaultBtn").onclick=async()=>{const d=await db();d.transaction("assets","readwrite").objectStore("assets").clear();renderVault()};

async function selectedPng(){const b=await canvas.toBlob({format:"png",multiplier:1});if(!b)throw new Error("PNG export unavailable");lastBlob=b;return b}
function download(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}
$("exportBtn").onclick=async()=>{try{const b=await selectedPng(),o=canvas.getActiveObject(),name=((o?.name||"asset").replace(/\.[^.]+$/,"")||"asset")+".png";download(b,name);await vaultPut(b,name);toast("PNG exported")}catch(e){console.error(e);toast("Export failed")}};

async function getSelectedSourceBitmap(){const o=canvas.getActiveObject();if(!o||o.type!=="image")throw new Error("Select a sprite sheet image first");return{o,src:o.getElement()}}
$("framesBtn").onclick=async()=>{try{const{o,src}=await getSelectedSourceBitmap(),cols=Math.max(1,+$("cols").value||1),rows=Math.max(1,+$("rows").value||1),cw=Math.floor((src.naturalWidth||o.width)/cols),ch=Math.floor((src.naturalHeight||o.height)/rows),base=(o.name||"frames").replace(/\.[^.]+$/,"");recentFrames=[];let count=0;for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const out=document.createElement("canvas");out.width=cw;out.height=ch;out.getContext("2d").drawImage(src,c*cw,r*ch,cw,ch,0,0,cw,ch);const b=await new Promise(res=>out.toBlob(res,"image/png",1));recentFrames.push(b);await vaultPut(b,base+"_"+String(++count).padStart(3,"0")+".png")}toast(count+" frames extracted and ready to pack")}catch(e){console.error(e);toast(e.message||"Frame extraction failed")}};
$("sheetBtn").onclick=async()=>{try{if(!recentFrames.length)throw new Error("Extract frames first");const cols=Math.max(1,+$("cols").value||1),rows=Math.max(1,+$("rows").value||1),count=Math.min(recentFrames.length,cols*rows),first=await createImageBitmap(recentFrames[0]),fw=first.width,fh=first.height,out=document.createElement("canvas");out.width=fw*cols;out.height=fh*rows;const ctx=out.getContext("2d");for(let i=0;i<count;i++){const bm=i===0?first:await createImageBitmap(recentFrames[i]);ctx.drawImage(bm,(i%cols)*fw,Math.floor(i/cols)*fh);if(i>0)bm.close()}first.close();const b=await new Promise(res=>out.toBlob(res,"image/png",1));download(b,"sprite-sheet.png");await vaultPut(b,"sprite-sheet.png");toast(count+" frame(s) packed into raster sheet")}catch(e){console.error(e);toast(e.message||"Sheet export failed")}};

$("undoBtn").onclick=async()=>{if(history.length<2)return;future.push(history.pop());await restore(history.at(-1))};$("redoBtn").onclick=async()=>{const n=future.pop();if(n){history.push(n);await restore(n)}};
$("newBtn").onclick=()=>{canvas.clear();history=[];future=[];snapshot();$("dropHint").style.display="block";$("docName").textContent="Untitled Asset";toast("New asset")};
$("saveBtn").onclick=()=>{const data={version:2,width:+$("cw").value,height:+$("ch").value,canvas:canvas.toJSON(["name","assetId"])};download(new Blob([JSON.stringify(data)],{type:"application/json"}),"asset-forge-project.json");toast("Project saved")};
$("openBtn").onclick=()=>$("projectInput").click();$("projectInput").onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const d=JSON.parse(await f.text());$("cw").value=d.width;$("ch").value=d.height;resizeEditor();await restore(JSON.stringify(d.canvas));$("dropHint").style.display="none";toast("Project opened")}catch(err){console.error(err);toast("Project file invalid")}};
$("applySize").onclick=()=>{resizeEditor();snapshot()};
function togglePanel(id){$(id).classList.toggle("open")};$("toolsToggle").onclick=()=>togglePanel("toolPanel");$("propsToggle").onclick=()=>togglePanel("propsPanel");

function b64(blob){return new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(fr.result.split(",")[1]);fr.onerror=rej;fr.readAsDataURL(blob)})}
async function githubFetch(path,options={}){if(!github)throw new Error("GitHub is not connected");const res=await fetch("https://api.github.com/repos/"+github.repo+"/contents/"+path+"?ref="+encodeURIComponent(github.branch),{...options,headers:{"Accept":"application/vnd.github+json","Authorization":"Bearer "+github.token,...(options.headers||{})}});const txt=await res.text();let data=null;try{data=JSON.parse(txt)}catch{}if(!res.ok)throw new Error(data?.message||"GitHub API "+res.status);return data}
async function loadRepoAssets(){if(!github)return toast("Connect GitHub first");setStatus("Loading repository assets…");try{const data=await githubFetch(github.folder);const files=Array.isArray(data)?data.filter(x=>x.type==="file"&&/\.(png|jpe?g|webp|avif)$/i.test(x.name)):[];for(const f of files){const res=await fetch(f.download_url);if(res.ok){const blob=await res.blob();await vaultPut(blob,f.name,true)}}await renderVault();setStatus("Ready");toast(files.length+" repository assets loaded")}catch(e){console.error(e);setStatus("Ready");toast("Repository load failed: "+e.message)}}
$("repoBtn").onclick=()=>{$("githubModal").classList.remove("hidden");if(github){$("repoName").value=github.repo;$("repoBranch").value=github.branch;$("repoFolder").value=github.folder}};
$("connectRepoBtn").onclick=async()=>{const token=$("repoToken").value.trim(),repoName=$("repoName").value.trim(),branch=$("repoBranch").value.trim()||"main",folder=($("repoFolder").value.trim()||"assets").replace(/^\/+|\/+$/g,"");if(!token||!repoName)return toast("Repository and token are required");github={token,repo:repoName,branch,folder};$("repoStatus").textContent="Connected: "+repoName+" @ "+branch;$("pushBtn").disabled=false;$("githubModal").classList.add("hidden");toast("GitHub connected");await loadRepoAssets()};
$("refreshRepoBtn").onclick=async()=>{const token=$("repoToken").value.trim();if(!github&&token){github={token,repo:$("repoName").value.trim(),branch:$("repoBranch").value.trim()||"main",folder:($("repoFolder").value.trim()||"assets").replace(/^\/+|\/+$/g,"")}}if(!github)return toast("Connect GitHub first");await loadRepoAssets()};
$("pushBtn").onclick=async()=>{const o=canvas.getActiveObject();if(!o||o.type!=="image")return toast("Select an image asset first");const b=await selectedPng(),safe=((o.name||"asset").replace(/[^a-z0-9._-]+/gi,"_")||"asset").replace(/\.png$/i,"")+".png",path=github.folder+"/"+safe;setStatus("Saving to GitHub…");try{let sha;try{const old=await githubFetch(path);sha=old.sha}catch{}const body=JSON.stringify({message:"Asset Forge: save "+safe,content:await b64(b),branch:github.branch,...(sha?{sha}:{})});const res=await fetch("https://api.github.com/repos/"+github.repo+"/contents/"+path,{method:"PUT",headers:{"Accept":"application/vnd.github+json","Authorization":"Bearer "+github.token,"Content-Type":"application/json"},body});const data=await res.json();if(!res.ok)throw new Error(data?.message||"Upload failed");setStatus("Ready");toast("Saved to GitHub: "+path);await loadRepoAssets()}catch(e){console.error(e);setStatus("Ready");toast("GitHub save failed: "+e.message)}};

window.AssetForgeAgent={
  status:()=>{const o=canvas.getActiveObject(),el=o?.type==="image"?o.getElement():null;return {canvas:{width:canvas.width,height:canvas.height},objects:canvas.getObjects().length,selected:o?.name||null,selectedSize:el?{width:el.naturalWidth||o.width,height:el.naturalHeight||o.height}:null,github:!!github};},
  upload:addRasterBlob,
  removeBackground:removeBg,
  cropSelected:async(x,y,w,h)=>{const o=canvas.getActiveObject();if(!o||o.type!=="image")throw new Error("Select image");return imageFromCrop(o,x,y,w,h)},
  trimSelected:trimTransparent,
  exportPng:selectedPng,
  saveSelectedToGitHub:async()=>{if(!$("pushBtn").disabled)return $("pushBtn").click();throw new Error("GitHub is not connected")},
  loadGitHubAssets:loadRepoAssets
};

canvas.on("object:added",()=>{if(!restoring)snapshot();syncProps()});canvas.on("object:modified",()=>{if(!restoring)snapshot();syncProps()});canvas.on("selection:created",syncProps);canvas.on("selection:updated",syncProps);canvas.on("selection:cleared",syncProps);
document.onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="z"){e.preventDefault();$("undoBtn").click()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="y"){e.preventDefault();$("redoBtn").click()}if(e.key==="Delete"&&document.querySelector(".modal:not(.hidden)")===null)$("deleteBtn").click()};
$("brightness").value=$("contrast").value=$("saturation").value=$("blur").value=0;
resizeEditor();snapshot();renderVault();